### ISSUE TITLE
Linked Data Templates

### ISSUE THREAD

**Issue by namedgraph** [gklyne/annalist#48]
Hi Graham,

what is status of Annalist? I was pointed to the project by @stain.

I wonder if you can see some parallels with your approach and the LDT specification we have developed: https://atomgraph.github.io/Linked-Data-Templates/

We have also developed a platform based on the LDT technolgoy.

**Comment by gklyne** [comment]
Oops, sorry, I only just noticed this issue.  Sorry for the silence.

Status is (as of Feb 2019): I'm working towards a "V1.0" release based pretty much on current functionality, with bug fixing and deployment hardening being current priorities.  I'm also using Annalist quite actively myself for linked data prototyping.

There do appear to be parallels with LDT.  The main difference, as I see it based on a quick cursory scan of the LDT document, is that Annalist is aimed at non-programmers.  The underlying data model and its presentation are all configurable through the web interface.  Annalist a self-standing application rather than a specification (though also used in conjunction with other web/linked data applications).  The survey in [1] discusses Annalist goals and compares them with some other applications - the analysis there might help.

[1] https://github.com/gklyne/annalist/blob/master/documents/publications/LDOW2016-paper/Annalist-paper-ACMSIG.pdf
     - It appears that the link from the LDoW workshop proceedings is broken :(.  I'll add this GitHub link to the annalist.net page.
